### ISSUE TITLE
Port Java architecture to pyGeppetto

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.python#21]
While at the moment pyGeppetto has the equivalent API of org.geppetto.model it is still missing the managers and the middleware code that controls the various services.

**Comment by aranega** [comment]
Hi @tarelli ,

Indeed! I started to work on it on the [`feature/manager`](https://github.com/openworm/pygeppetto/tree/feature/managers/pygeppetto) branch. Sorry I have less time recently, the new job take me a lot of time, but I start to balance everything! From what I started, for the first version I was working on, I tried to match the same behavior than the Java version and add tests. When the first version will be finished, it will be possible to refactor everything with the tests :).

Sorry again for the delay...

**Comment by tarelli** [comment]
Now worries and thanks for the update @aranega! We might also be able to help you out in the next weeks if you want.

**Comment by filippomc** [comment]
Hi @aranega, we again came across this porting, it would help much with what we're doing. We are actually implementing the lazy loading through the importValue logic. Do you think is a good idea starting  from this branch?

**Comment by aranega** [comment]
Hi @filippometacell, are you refering to the experimental feature regarding performances or the started work about the Geppetto managers?
If that's the Geppetto manager, it could be a good idea to start from this branch. I need to find time to continue (work is really time consuming since few months...). 
If that's the experimental patch branch, yes, you could. I will try to match thoses performances in PyEcore, but I don't know if I will be able to reach exactly this point. At the end, you should not see any modification or regression in the API beside a slow down (hopefully, not so much of a slowdown...)

**Comment by filippomc** [comment]
Hi @aranega I'll need both for sure at some point :) here I was wondering about starting something from the Geppetto managers branch adding some features related to the importValue flow, hopefully without bothering you for other than some advice. I'm opening a new issue for that specifically.. Thanks!
