### ISSUE TITLE
Porting EMapGeppettoSerializer.java to pygeppetto

### ISSUE THREAD

**Issue by rodriguez-facundo** [openworm/org.geppetto.python#25]
Hi @aranega, I think we are missing the serialization for Maps that we have in [Java](https://github.com/openworm/org.geppetto.core/blob/master/src/main/java/org/geppetto/core/model/EMapGeppettoSerializer.java). And that is causing some troubles to get the axis label for plots in NWB-Explorer. I would like to port the serialization to `pygepetto`. I wonder if you have like a template so I can get a boost to start with it 😄.

<img width="1665" alt="Screenshot 2019-04-10 at 8 15 34 AM" src="https://user-images.githubusercontent.com/32278395/55883356-9081aa80-5b7c-11e9-9491-d466c46b36b7.png">

cc: @filippometacell @tarelli

**Comment by tarelli** [comment]
https://github.com/openworm/org.geppetto.core/blob/master/src/main/java/org/geppetto/core/model/GeppettoSerializer.java That is the serializer I wrote in Java that is customised with few things (the syncable and the emap custom serializers) is there an equivalent facility on pyEcore?:) Thanks!

**Comment by aranega** [comment]
@rodriguez-facundo I will check for that, indeed, as Matteo reported, it is a custom serialization point.

@tarelli Thanks a lot for the code! I will see asap what I can do. I know I let some entry points in the JSON serialization, but perhaps not for that. Sorry about the inconvenience... I will try to find a solution as quickly as I can.

**Comment by aranega** [comment]
Ok, I checked. I'm afraid that there is no mechanism to currently support that for the JSON serialization in PyEcore, but I could add a specific mechanism for that. I will try to add this asap. Perhaps this week-end? I have some ideas for that.

**Comment by tarelli** [comment]
@aranega thanks so much Vincent, let us know if you want help testing anything!

**Comment by aranega** [comment]
@tarelli Thanks so much! I'm currently working on a way of adding custom serialization for object on a dedicated branch. At the moment, I did the serialization part, I need to work more on the deserialization part, I was not happy with the design I had. In a general way, I'm not so happy with the solution, even if it will work without issues. 
I think I will not document it until I find a better solution (using the default json deserialization mechanism provided by Python) and let this only for you guys so you can deal with everything :).

I will try to have a version very quickly. The logic will be a little bit different from the one existing in emfjson, but you should be able to do provide a similar json at the end.

**Comment by tarelli** [comment]
@aranega great, looking forward to it, thanks! :)

**Comment by rodriguez-facundo** [comment]
Hi @aranega, I can visualise the units label in the plot axis now, so I don't have the initial issue anymore. 

Note: below there is an example of how to pass a custom class to `json.dumps` in order to serialise specific classes in a custom way (example is for complex numbers). I think this approach would be easy to extend for pygeppetto users, but it is more related to pyecore than pygeppetto I guess 🙃. 

```
import json
class ComplexEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, complex):
            return [obj.real, obj.imag]
        return json.JSONEncoder.default(self, obj)
```

```
json.dumps(2 + 1j, cls=ComplexEncoder)
>>> '[2.0, 1.0]'
```

**Comment by rodriguez-facundo** [comment]
Hi @aranega, I opened a [PR](https://github.com/pyecore/pyecore/pull/63)  to custom_json_mapper because I needed to modify the serializer in pygeppetto like [this](https://github.com/openworm/pygeppetto/blob/feature/importvalue/pygeppetto/model/model_serializer.py).  No need to merge this. Let me know what would be more appropriated.

cc: @tarelli

**Comment by aranega** [comment]
@rodriguez-facundo Thanks for the modification proposals, they seems fine to me. I misread the original registration of the class and thought it was performed using a class and not an instance of a serializer. However, I will keep the dict as object mappers because you could want to register many different mappers for different types in the same resource. I will do a mix between your proposal and the original one I had. Thanks a lot!

About the classic JSON custom deserializer (provided by Python), the issue I had with it was that for each object deserialization I also need more information like the feature that contains the object in order to perform a good serialization. I need to dig more, perhaps I can pass new parameters to it.

I will try to tackle the JSON deserialization part today. I hope I will have a better version during the day, the one I had were not great.

**Comment by aranega** [comment]
@rodriguez-facundo @tarelli .... Ok, I'm very tired... I was struggling in finding a good way of proposing a good API for custom deserialization, but I saw in your code that actually, you don't need it. You only need the serialization part, am I right?  I think I totally misread parts of the Java code... I'm really sorry about that...

If that's the case, with the modifications proposed by @rodriguez-facundo and the ones I made today, everything should be good (beside testing on my side) and I will be able to release a new version today (it will be a minor version in order to not emphasize the modifications on the code).

**Comment by filippomc** [comment]
Hi @aranega thanks for you help, I'm doing a bit of tests putting it all together. The new api is perfect for our needs and I like to have the dictionary to have control of the registered mappers. I can also confirm we don't need deserialization for what we're doing.

I can only suggest a little improvement: with java the mapper is used for all subclasses for a given type. I'm going with this map selection now which does the same:

`mapper = next((self.mappers[k] for k in self.mappers if issubclass(cls, k)), self.default_mapper)`

What do you think?

**Comment by rodriguez-facundo** [comment]
Thanks a lot @aranega. All good from my side.

**Comment by aranega** [comment]
@rodriguez-facundo I'm glad everyting's fine :) Thanks!

@filippometacell That's a great idea, thanks a lot, I had it right away. Sorry for the delay, I will write tests and push a new version as soon as they are ready. For the Python 2 version, I will take a little bit of time, I let this version a little bit behind and I need to resync everything with the Python 3 version.

**Comment by aranega** [comment]
@rodriguez-facundo @filippometacell @tarelli I released a new version of PyEcore for Python 3 with the custom serialiser support and the modification proposed by @filippometacell . Tell me if it works for you.

Again, sorry for the delay...
