### ISSUE TITLE
Missing data when serializing

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.python#5]
Hi @aranega 
I am trying to replicate a model we have in Java with pygeppetto. All is going well but I'm hitting a problem.
I have this bit of code:

```python
        type = pygeppetto.CompositeType(id='cell',name='cell')
        visualType = pygeppetto.CompositeVisualType(id='cellMorphology',name='cellMorphology')
        type.visualType=visualType
        visualType.variables.append(self.factory.createCylinder('apical0_1', bottomRadius=3.0, topRadius=3.0, position=Point(y=17.0), distal=Point(y=77.0)))
        visualType.variables.append(self.factory.createCylinder('apical1_5', bottomRadius=1.5, topRadius=1.5, position=Point(y=77.0), distal=Point(x=-150.0,y=77.0)))
        visualType.variables.append(self.factory.createCylinder('apical2_2', bottomRadius=2.2, topRadius=2.2, position=Point(y=77.0), distal=Point(y=477.0)))
        visualType.variables.append(self.factory.createCylinder('apical2_2', bottomRadius=1.45, topRadius=1.45, position=Point(y=477.0), distal=Point(y=877.0)))
        visualType.variables.append(self.factory.createCylinder('basal2_8', bottomRadius=2.5, topRadius=2.5, position=Point(y=-50.0), distal=Point(x=-106.07,y=-156.07)))
        visualType.variables.append(self.factory.createCylinder('basal1_7', bottomRadius=2.5, topRadius=2.5, position=Point(y=-50.0), distal=Point(x=-106.07,y=-156.07)))
        visualType.variables.append(self.factory.createCylinder('basal0_6', bottomRadius=2.0, topRadius=2.0, distal=Point(y=-50.0)))
        visualType.variables.append(self.factory.createCylinder('soma_0', bottomRadius=11.5, topRadius=11.5, distal=Point(y=17.0)))
        visualType.variables.append(self.factory.createCylinder('apical4_4', bottomRadius=11.5, topRadius=11.5, position=Point(y=877.0),distal=Point(y=1127.0)))
        print visualType.variables
```
the last print results in: 
```
EOrderedSet([<model.variables.variables.Variable object at 0x10cd8ee50>, <model.variables.variables.Variable object at 0x10d1df290>, <model.variables.variables.Variable object at 0x10d1df650>, <model.variables.variables.Variable object at 0x10d1dfa10>, <model.variables.variables.Variable object at 0x10d1dfe10>, <model.variables.variables.Variable object at 0x10d1e5250>, <model.variables.variables.Variable object at 0x10d1e5590>, <model.variables.variables.Variable object at 0x10d1e58d0>, <model.variables.variables.Variable object at 0x10d1e5c90>])
```
however when I go to serialize the model inside the visualType there is no trace of the variables, see below:

```json
      "types": [
        {
          "visualType": {
            "eClass": "CompositeVisualType", 
            "$ref": "/"
          }, 
          "eClass": "CompositeType", 
          "name": "cell", 
          "id": "cell"
        }
      ], 
```

am I doing something wrong?

Btw createCylinder is just a small factory function I wrote:
```python
    def createCylinder(self, id, bottomRadius=1,topRadius=1,position=Point(),distal=Point()):
        variable = Variable(id=id)
        cylinder = Cylinder(bottomRadius=bottomRadius, topRadius=topRadius)
        cylinder.distal=distal
        cylinder.position=position
        variable.initialValues=TypeToValueMap(self.geppetto_common_library.types[8],cylinder)
        return variable
```
but given the stuff is there with a normal print I guess the problem is elsewhere.
Thanks for the help!

**Comment by aranega** [comment]
Hi @tarelli,

I'm glad the JSON serialization works now for you! Regarding this issue, it could come from the root element you choosed to serialize. 

From what I see, the `visualType` reference must not be a composite reference in the Geppetto metamodel (the JSON serialization uses a `$ref` to serialize it). The fact that the path towards the `CompositeVisualType` instance is only `/` would indicate that the instance is not contained in a `Resource` when the model is serialized. 
In which container is added `type`? Is `variable` added to any container?

I'm going to check the metamodel to see if I missed something or not. (Also, perhaps naming your var `type` could perhaps 'mask' the builtin `type` method, I don't know if this could implies some side-effects, but I would go with the missing container)

**Comment by aranega** [comment]
@tarelli So, I checked, and indeed, `visualType` is not a containment, so if the instance is not added in a container, and this container is not the root of the model), you will not have the  `CompositeVistualType` instance added inside the serialized JSON.

Also, I saw that you use:

```python
variable.initialValues=TypeToValueMap(self.geppetto_common_library.types[8],cylinder)
```

but `initialValues` is a `0..*` reference, so `.append(...)` should be used instead of `=`. However, this is also a regression from PyEcore which should throw an exception at runtime. I will correct this and ship it in the next version.

**Comment by tarelli** [comment]
@aranega puff silly me, I thought I had containment of the visual type by the type but rightfully it's just a reference, I added the visualType to the library and now I'm having another issue.

TypeError: 'TypeToValueMap' object is not iterable

This happens when I try to add the model to the resource and it's probably due to how I am using the TypeToValueMap
How am I meant to do the equivalent of this?
```java
variable.getInitialValues().put(visualType, cylinder);
```
python?
```python
variable.initialValues=??(self.geppetto_common_library.types[8],cylinder)
```
Thanks again!

**Comment by tarelli** [comment]
@aranega oh ok, so this
`
variable.initialValues.append(TypeToValueMap(self.geppetto_common_library.types[8],cylinder))
`
but requires a fix?

**Comment by tarelli** [comment]
@aranega no exceptions here, it serialized well I think?

```json
 {
              "initialValues": [
                {
                  "key": {
                    "eClass": "VisualType", 
                    "$ref": "//@libraries.0/@types.8"
                  }, 
                  "eClass": "TypeToValueMap", 
                  "value": {
                    "position": {
                      "y": 477.0, 
                      "eClass": "Point"
                    }, 
                    "topRadius": 1.45, 
                    "distal": {
                      "y": 877.0, 
                      "eClass": "Point"
                    }, 
                    "eClass": "Cylinder", 
                    "bottomRadius": 1.45
                  }
                }
              ], 
              "eClass": "Variable", 
              "id": "apical2_2"
            }, 
```

**Comment by aranega** [comment]
@tarelli That's it! Indeed, an exception should have been raised with the `=` during assignement. Due to the way I serialize the JSON, the code would serialize without issue (and probably deserialize without issue also), but this is possible that still using the `=`, the serialized JSON would have been problematic for Java. I'm on it! (I will release this fix probably later however is it is not a "blocking" one).

Regarding `Map` with PyEcore, it is not well supported, as you saw, you have to create the "entry" relation: `TypeToValue` in your case, and add it as if it is a collection. This way of dealing with elements is very close from the way QVTo and OCL based langage do the stuff, so it is acceptable, but
I need to work on that in future PyEcore version (in order to provide a real `dict` like implementation for those cases).

**Comment by tarelli** [comment]
@aranega got it, yes that's why I wasn't sure how to use it but as long as there's a way to do it for now it's good enough for me, thanks so much Vincent.

**Comment by aranega** [comment]
@tarelli My pleasure, I'm glad this could help you! However, please check that the serialized JSON can be well deserialized by Java (I hope so).

**Comment by adrianq** [comment]
Hi @aranega! Something related to this... I was playing around with @tarelli code and changing it a bit and I just noticed that 0.0 values are not serialized properly.

This is some sampling code
```
visualType.variables.append(self.factory.createSphere(sec_name,
  radius=float(points[i][3] / 2),
  position=Point(x=1.0,y=1.0, z=0.0)))
```

and this is the serialised json I am currently getting:
```
          "variables": [
            {
              "initialValues": [
                {
                  "value": {
                    "position": {
                      "y": 1.0, 
                      "x": 1.0, 
                      "eClass": "Point"
                    }, 
                    "radius": 9.4, 
                    "eClass": "Sphere"
                  }, 
                  "eClass": "TypeToValueMap", 
                  "key": {
                    "eClass": "VisualType", 
                    "$ref": "//@libraries.0/@types.8"
                  }
                }
              ], 
              "eClass": "Variable", 
              "types": [
                {
                  "eClass": "VisualType", 
                  "$ref": "//@libraries.0/@types.8"
                }
              ], 
              "id": "soma"
            }
          ]
```

as you can see there is no 'z' value.

I saw serialisation is performed [in this class](https://github.com/openworm/pygeppetto/blob/development/model/model_serializer.py) but to be honest I prefer to ask you before getting crazy looking at the code. Is this the expected behaviour or should we tune the serialization process?

**Comment by aranega** [comment]
Hi @adrianq!

Indeed, the behaviour is expected, the serializer only serializes data that are different from the datatype's default one. As in this case, `0.0` is the default value for floats, the serializer does not write it down, but the value is properly loaded once deserialized. I will check if the behaviour is the same for emf-jackson as soon as I get access to a computer. Should the data appear in the json? The idea is to save some space in the produced json by removing information that can be found in the metamodel.

**Comment by aranega** [comment]
@adrianq I checked with Java `emf-jackson` and the results are the same as the ones PyEcore provides. The `0.0` is not serialized as it represents the default value. I checked with `EFloat`, `EDouble` and `Double` from the XMLTypes library, and the result is always the same.

**Comment by adrianq** [comment]
Thanks for the quick reply @aranega! I understand now. The problem is that we are no getting the 0.0 in javascript:
![screenshot from 2017-11-24 14-16-31](https://user-images.githubusercontent.com/6850223/33214110-6bd5acf8-d122-11e7-969c-6060810e90ea.png)

and therefore the structure (a sphere representing the soma) is not properly displayed in 3D. I guess this is something we will have to address javascript side. Probably assuming a 0 when no property is found.

**Comment by aranega** [comment]
I see, indeed, that could be a solution. But, assuming that the default value for "no value" is `0.0` couldn't be tricky in some cases? (for other relations) 

Another solution would be to change the metamodel so the `eAttribute` is not `Double`, but  `DoubleObject` instead (or `EDoubleObject` if you want to stick with default Ecore's types). With the `xxxObject` types, the default value is `null`, so a set of `0.0` would force it's serialization. This would produce the result you want, but in another hand, it will perhaps break some of your already serialized models (as no property will be found for some `Point` instances, it will load `null` instead of `0.0`).

I really don't know which solution is the best in your case.

EDIT> The second solution would also requires a small adjustment in PyEcore side, and a metamodel code re-generation, but this is not a big issue for me, retro-compatibility issues sounds more problematic.

**Comment by adrianq** [comment]
Well, I meant to assume a 0.0 just for the coordinates of sphere and cylinders. Actually, I think we are already doing it in some bits of the code. I will look a bit more into the code... I see your point on changing the data type but I think it would have a bigger impact.

**Comment by tarelli** [comment]
@aranega @adrianq in EMFJSON we do this (I think I had to ask for this option to be added at the time)
 
```Java
		ResourceSetImpl resourceSet = new ResourceSetImpl();
		resourceSet.getPackageRegistry().put(GeppettoPackage.eNS_URI, GeppettoPackage.eINSTANCE);
		resourceSet.getResourceFactoryRegistry().getExtensionToFactoryMap().put("*", new JsonResourceFactory());

		Map<String, Object> options = new HashMap<>();
		options.put(EMFJs.OPTION_SERIALIZE_DEFAULT_VALUE, true);

		JacksonOptions jacksonOptions = new JacksonOptions.Builder().withTypeSerializer(customTypeSerializer).build(options);
```

**Comment by aranega** [comment]
@tarelli I will see what I can do about this, I hope the addition of this option will not result in an overly huge model with PyEcore.

**Comment by aranega** [comment]
@tarelli Ok, I got something, it was surprisingly easy to implement thanks to the generated code and a PyEcore bug which was always storing the modified references when required.
So, I added the ability to add an option as for the EMF resources. Here is a code example that shows how the code becomes (without all the proper imports, I only added the new ones):

```python
# [...] other imports
from pyecore.resources.json import JsonResource, JsonOptions

rset = ResourceSet()
rset.resource_factory['json'] = lambda x: JsonResource(x, indent=2)

resource = rset.create_resource('test.json')

p = pygeppetto.values.Point(x=0.0, y=0.0)  # no 'z' to show the partial serialization

resource.append(p)
resource.save(options={JsonOptions.SERIALIZE_DEFAULT_VALUES: True})
```

And here the produced JSON:

```json
{
  "y": 0.0, 
  "x": 0.0, 
  "eClass": "https://raw.githubusercontent.com/openworm/org.geppetto.model/development/src/main/resources/geppettoModel.ecore#//values/Point"
}
```

I just need to write some tests to ensure everything's fine for dynamic metamodel also (should be, but I only tested this manually), backport this into `pyecore-py2` and it will be good.

**Comment by tarelli** [comment]
Thanks @aranega you're a saviour :)

**Comment by aranega** [comment]
@tarelli @adrianq I had time today to write tests and release a new PyEcore version. The `pyecore-py2` 0.7.6 is now available and supports the `SERIALIZE_DEFAULT_VALUES` option exactly how I showed in my previous message ;).

**Comment by adrianq** [comment]
Many thanks @aranega ! Seems to be working fine:
![screenshot from 2017-11-27 13-28-17](https://user-images.githubusercontent.com/6850223/33268949-ecb57c08-d376-11e7-9723-48b16c31323e.png)
